# Jekyll configuration
config:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
markdown: kramdown
sass:
  style: compressed
exclude: [vendor,gems]

# Site settings
title: 'BuildingSync'
title_html: 'BuildingSync<sup>®</sup>'
description: 'Standardizing Energy Audit Data Collection'
language: 'en-us'
baseurl: ''
url: 'http://buildingsync.net/'
google_analytics: UA-18838154-16
